### ISSUE TITLE
when i run the demo, there occured an error in function warpImg, can anyone help? thx

### ISSUE THREAD

**Issue by xiaozhao00** [iacopomasi/face_specific_augm#23]
Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    demo()
  File "demo.py", line 92, in demo
    model3D.ref_U, eyemask, model3D.facemask, opts)
  File "/home/joey/Downloads/pycharm_projects/face_specific_augm-master/renderer.py", line 109, in render
    frontal_raw = warpImg(img, ref_U.shape[0], ref_U.shape[1], prj_jnt, ind_jnt)
  File "/home/joey/Downloads/pycharm_projects/face_specific_augm-master/renderer.py", line 25, in warpImg
    np.squeeze( np.asarray( prj[1,:] ) ).astype('float32'),  cv2.INTER_CUBIC)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/imgwarp.cpp:1749: error: (-215) dst.cols < 32767 && dst.rows < 32767 && src.cols < 32767 && src.rows < 32767 in function remap

**Comment by iacopomasi** [comment]
The project does not support OpenCV3 though there is an unmerged PR that supports OpenCV3.
