### ISSUE TITLE
ValueError: too many values to unpack 

### ISSUE THREAD

**Issue by akshayjaryal603** [iacopomasi/face_specific_augm#25]
> Preloading all the models for efficiency
> Loading pose model in model3D_aug_-00_00_01.mat
Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    demo()
  File "demo.py", line 48, in demo
    allModels = myutil.preload(this_path,pose_models_folder,pose_models,nSub)
  File "/home/akshay/augmented/face_specific_augm-master/myutil.py", line 66, in preload
    model3D = ThreeD_Model.FaceModel(this_path + pose_models_folder + pose, 'model3D', True)
  File "/home/akshay/augmented/face_specific_augm-master/ThreeD_Model.py", line 15, in __init__
    self.eyemask = self.getEyeMask(width=8,plot=False)
  File "/home/akshay/augmented/face_specific_augm-master/ThreeD_Model.py", line 38, in getEyeMask
    output1 = self.createMask(eyeLeft, width=width)
  File "/home/akshay/augmented/face_specific_augm-master/ThreeD_Model.py", line 64, in createMask
    contours, hierarchy = cv2.findContours(eyemask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

**Comment by iacopomasi** [comment]
I think this is OpenCV version problem. Try using OpenCV version 2.

**Comment by akshayjaryal603** [comment]
Write now I have a version "3.2.0" of "Opencv" in my laptop. Can you please guide me for uninstalling this version and installing Opencv2.

**Comment by iacopomasi** [comment]
You can install a virtual env in python and switch to the other OpenCV version in that virtual environment. I am sure if you search online there is a tutorial for this or something similar to this.
