### ISSUE TITLE
Dlib, opencv and imutils version

### ISSUE THREAD

**Issue by kevinzezel** [iacopomasi/face_specific_augm#33]
Please, what is the version of Dlib, opencv and imutils ?

**Comment by kevinzezel** [comment]
I got this error:

Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    demo()
  File "demo.py", line 92, in demo
    model3D.ref_U, eyemask, model3D.facemask, opts)
  File "/home/magna/Kevin/Proc img/face_specific_augm-master/renderer.py", line 109, in render
    frontal_raw = warpImg(img, ref_U.shape[0], ref_U.shape[1], prj_jnt, ind_jnt)
  File "/home/magna/Kevin/Proc img/face_specific_augm-master/renderer.py", line 25, in warpImg
    np.squeeze( np.asarray( prj[1,:] ) ).astype('float32'),  cv2.INTER_CUBIC)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:1724: error: (-215:Assertion failed) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function 'remap'

**Comment by iacopomasi** [comment]
Hi @kevinzezel ,
it seems you are using OpenCV 4.2, please try to use an older OpenCV version like 2.4.0 and it should work.

I hope this helps.
